### ISSUE TITLE
Invalid checkpoint link

### ISSUE THREAD

**Issue by chethanluffy** [zhangganlin/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation#1]
The given checkpoint's download link isn't working.
Kindly provide updated link.
Thanks

**Comment by zhangganlin** [comment]
Hi, 

Thansk for pointing it out. I have upload the checkpoint file in the "trained" folder and update the readme. If it still doesn't work, I can also give the google drive link which is 
[https://drive.google.com/file/d/1mSBkUJN45rHxFdov6a8osIyrbMQy8DFq/view?usp=sharing](https://drive.google.com/file/d/1mSBkUJN45rHxFdov6a8osIyrbMQy8DFq/view?usp=sharing )
Hope it works.

Ganlin
