### ISSUE TITLE
请问这个项目有相应的论文吗 感谢！

### ISSUE THREAD

**Issue by flyxuexi** [zhangganlin/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation#3]

**Comment by zhangganlin** [comment]
你好，这个项目是我们做的课程项目，所以没有发表，但可以参考我们的项目报告
https://github.com/zhangganlin/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation/blob/main/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation.pdf

**Comment by flyxuexi** [comment]
> 你好，这个项目是我们做的课程项目，所以没有发表，但可以参考我们的项目报告 https://github.com/zhangganlin/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation/blob/main/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation.pdf

好的 谢谢！
