### ISSUE TITLE
前辈，还想请问这篇改进是不是也参考了StereoDRNet呢，这个论文同样提到了扩张卷积模块，不过没开源

### ISSUE THREAD

**Issue by flyxuexi** [zhangganlin/Improved-PSMNet-for-Deep-Stereo-Disparity-Estimation#5]

**Comment by zhangganlin** [comment]
同学你好，是的，我们的结构也参考了StereoDRNet，在我们的report的参考文献 [14] 有提到

**Comment by flyxuexi** [comment]
谢谢前辈，请问您有没有尝试将扩张卷积模块加入到psm以外的模型呢，我加到了mobilestereonet3d中，epe指标是下降的，但是上传到官方kitti2015中，返回的测试结果是比论文中差的，请问您有没有遇到类似的情况呢？谢谢，stereodrnet的kitti2015测试结果也不太好，这是扩张卷积的特性造成的吗？

**Comment by zhangganlin** [comment]
这些我们都没有试过。关于扩张卷积的影响，我自己目前也不太做这个领域，所以其实不是特别了解，不好意思

**Comment by flyxuexi** [comment]
> 这些我们都没有试过。关于扩张卷积的影响，我自己目前也不太做这个领域，所以其实不是特别了解，不好意思

嗯嗯，还是谢谢
